apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: nats-source-e2e
spec:
  vertices:
    - name: in
      scale:
        min: 2
      volumes:
        - name: my-secret-mount
          secret:
            secretName: nats-auth-fake-token
      source:
        udsource:
          container:
            image: quay.io/numaio/numaflow-source/nats-source:v0.5.4
            env:
              - name: NATS_CONFIG
                value: |
                  url: nats
                  subject: test-subject
                  queue: my-queue
                  auth:
                    token:
                      localobjectreference:
                        name: nats-auth-fake-token
                      key: fake-token
            volumeMounts:
              - name: my-secret-mount
                mountPath: /etc/secrets/nats-auth-fake-token
    - name: out
      sink:
        log: {}
  edges:
    - from: in
      to: out